### ISSUE TITLE
doc: Grade an Exercise

### ISSUE THREAD

**Issue by Lanietodev** [classroomio/classroomio#219]
### Improvement Description

A step-by-step guide on how admins can grade an exercise complete with visuals. This will contribute to ClassroomIO's doc.

### Rationale

It'll help ClassroomIO admins easily navigate the interface to grade exercises.

### Proposed Solution

It'll contain a very simple structure. It should follow documentation best practices to ensure it caters to user needs.

### Please check the boxes that apply to this improvement suggestion.

- [X] I have searched the existing issues and improvement suggestions to avoid duplication.
- [X] I have provided a clear description of the improvement being suggested.
- [X] I have explained the rationale behind this improvement.
- [X] I have included any relevant technical details or design suggestions.
- [X] I understand that this is a suggestion and that there is no guarantee of implementation.

**Comment by CBID2** [comment]
I'll work on this @rotimi-best

**Comment by rotimi-best** [comment]
@CBID2 sure please go for it
