### ISSUE TITLE
Student activity graph

### ISSUE THREAD

**Issue by rotimi-best** [classroomio/classroomio#244]
### Feature Description

- We should track activities of students and display a graph on their dashboard.

Activities like:
1. Completed lesson
2. Submitted exercise
3. Community post
4. Community response
5. Newsfeed post
6. News feed response
7. Live comment
8. Live poll

<img width="994" alt="image" src="https://github.com/rotimi-best/classroomio/assets/31730715/743c8772-7f05-4aa6-9d7a-b679608c926f">

### Please check the boxes that apply to this feature request.

- [ ] I have searched the existing feature requests to make sure this is not a duplicate.
- [ ] I have provided a detailed description of the requested feature.
- [ ] I have explained the use case or scenario for this feature.
- [ ] I have included any relevant technical details or design suggestions.
- [ ] I understand that this is a suggestion and that there is no guarantee of implementation.

**Comment by Raju-kadel-27** [comment]
@rotimi-best  Can you assign this to me ?

**Comment by rotimi-best** [comment]
@Raju-kadel-27 Sure.

Curious how you'd like to implement it.

**Comment by Raju-kadel-27** [comment]
@rotimi-best Currently, I have not explored the codebase yet . Would be much easier if you provide me some insights about the issue.

**Comment by rotimi-best** [comment]
@Raju-kadel-27 
Yeah sure I get it. I am more curious on a high level, how you would implement the data structure of the graph and a simple API to collect the data.

Implementing this feature would be a great advantage to the platform.

I am thinking you don't really even need to understand how the app works works, you just need to implement an endpoint in our backend to collect the data, store it and render this student graph

**Comment by Raju-kadel-27** [comment]
@rotimi-best we need to think scalability in mind right ? Will come back to you after some research.
If you have any pre-planned ways, you can share it to me ?

**Comment by rotimi-best** [comment]
@Raju-kadel-27 Yes.

Ideally some event driven system we could use to collect the data, store it the db and a GET endpoint that is cached to handle API requests.

It would be cool if we could also keep track of the activities of the students that we can show in graphs or table format.

For example we can have a leaderboard of the most active student in an organization and in what course they belong to.

**Comment by Raju-kadel-27** [comment]
@rotimi-best  
Sorry for late response, a bit busy at moment.
What do you think, if we create each tables for activities on RDMS , create necessary associations, record each events separately. 
When we want to display it on the graph, something like materialized view may come handy.
We are on supabase, right ?

**Comment by rotimi-best** [comment]
Yes we are using supabase for our db.

Heard a lot of things about clickhouse however I would say we keep things simple. I have also heard about Tinybird as well however my issue with having extra services is the work self hosters have to go through to setup our app.

Let's do DB for now and if we face issues in the future can move it away from the DB to a dedicated service. What do you think?

**Comment by Raju-kadel-27** [comment]
@rotimi-best  Yes, I think thats the best approach for now.

**Comment by rotimi-best** [comment]
Un-assigning you @Raju-kadel-27 cause of in activity
