### ISSUE TITLE
[Bug] No options visible in `How did you hear about us` section

### ISSUE THREAD

**Issue by vaishak10** [classroomio/classroomio#405]
### Issue Description

Once we for the first time and create and organisation and click on continue we get a `How did you hear about us` section where the users are allowed to choose options for `What brings you to` and `How did you hear about us` along with the option to select the preferred language. Here the options for these questions are not visible and also the preferred language select dropdown does not overlay to check all the language options. 

https://github.com/user-attachments/assets/fd780662-093c-4caf-b45f-ad22c9f24632

### Steps to Reproduce

1. Login and Create an account
2. Create and organisation and click continue
3. User will be asked to answer `How did you hear about us` and `What brings you to`. The options for these are not appearing

### Expected Behavior

The options for `How did you hear about us` and `What brings you to` should appear and user should be able to select the option along with that select the preffered language by checking the possible languages available.

### Current Behavior

`How did you hear about us` and `What brings you to` Options are not available and preffered language dropdown options are not visible until the user focuses on the dropdown.

### Operating System [e.g., Windows 10]

MacOS

### Browser [e.g., Chrome, Firefox]

Brave

### Environment (locally, production, selfhosted)

Production

### Please check the boxes that apply to this issue report.

- [X] I have searched the existing issues to make sure this is not a duplicate.
- [X] I have provided steps to reproduce the issue.
- [X] I have included relevant environment information.
- [ ] I have included any relevant screenshots.
- [X] I understand that this is a voluntary contribution and that there is no guarantee of resolution.
- [X] I want to work on creating a PR for this issue if approved

**Comment by vaishak10** [comment]
To the maintainer, I want to work on this issue!

**Comment by rotimi-best** [comment]
Maybe you have an extension that is hidding it? Not sure exactly what is going on cause you should be able to see them.

Sure you can go ahead to investigate it

**Comment by rotimi-best** [comment]
@vaishak10 What's up? are you interested in looking more into this?
