### ISSUE TITLE
Improvement on the testimonial after the hero section

### ISSUE THREAD

**Issue by EverPleroma** [classroomio/classroomio#464]
### Improvement Description

That section of the landing page looks like it is a sort of welcome speech from the founder. I believe making it look like a testimonial at first glance will give a better UX experience, where the user doesn't get it wrong at first.  
<img width="1440" alt="Screenshot 2024-09-06 at 01 09 16" src="https://github.com/user-attachments/assets/c2466828-bfdf-4e33-a08b-39b5159d6677">

### Proposed Solution

The apostrophe marks could be bigger.

### Please check the boxes that apply to this improvement suggestion.

- [X] I have searched the existing issues and improvement suggestions to avoid duplication.
- [X] I have provided a clear description of the improvement being suggested.
- [ ] I have explained the rationale behind this improvement.
- [X] I have included any relevant technical details or design suggestions.
- [X] I understand that this is a suggestion and that there is no guarantee of implementation.

**Comment by rotimi-best** [comment]
Done
