### ISSUE TITLE
Add 2 recommended blog post depending on current post tags

### ISSUE THREAD

**Issue by rotimi-best** [classroomio/classroomio#495]
### Feature Description

In every blog post there are tags, when we open a blog post at the bottom, let's add 2 recommended blog posts with similar tags

<img width="1274" alt="image" src="https://github.com/user-attachments/assets/51f9944f-d2ce-4c7a-bc76-91ab3530305a">

### Please check the boxes that apply to this feature request.

- [ ] I have searched the existing feature requests to make sure this is not a duplicate.
- [ ] I have provided a detailed description of the requested feature.
- [ ] I have explained the use case or scenario for this feature.
- [ ] I have included any relevant technical details or design suggestions.
- [ ] I understand that this is a suggestion and that there is no guarantee of implementation.

**Comment by Dun-sin** [comment]
hi @rotimi-best, what metrics do you think are best to use to decide which blog posts? Do you track users views on blog posts, or are the tags enough?

**Comment by rotimi-best** [comment]
@Dun-sin I think just blog post with related tags are fine.

For now we don't do any extra tracking

**Comment by Dun-sin** [comment]
> @Dun-sin I think just blog post with related tags are fine.
> 
> For now we don't do any extra tracking

got it, can i take this issue then?

**Comment by rotimi-best** [comment]
> > @Dun-sin I think just blog post with related tags are fine.
> > For now we don't do any extra tracking
> 
> got it, can i take this issue then?

most definitely. Thank you
