### ISSUE TITLE
Detect user language and change set initial locale of app 

### ISSUE THREAD

**Issue by rotimi-best** [classroomio/classroomio#529]
### Feature Description

- You will have a setting in your org to enable language auto detection.
- if toggled true, then we will determine the language
- set the language on the server
- however if you've set a language in your settings when you create an account, then that will override the browser detection

### Please check the boxes that apply to this feature request.

- [ ] I have searched the existing feature requests to make sure this is not a duplicate.
- [ ] I have provided a detailed description of the requested feature.
- [ ] I have explained the use case or scenario for this feature.
- [ ] I have included any relevant technical details or design suggestions.
- [ ] I understand that this is a suggestion and that there is no guarantee of implementation.

**Comment by rotimi-best** [comment]
For now will be keeping server language auto detection. I think this should be on by default because users using classroomio in other languages would want their course landing page to reflect their language for that particular audience.

>**Note**: menus and buttons are elements that we hard code the text and we can translate, however for other sections like the course description, these are only set by our users in a single language. Which means that part of the site can be in one language and other sections in another language.

A disadvantage of allowing automatic translation (for menus and buttons) is that for example, if my audience is portugese and someone from russia opens my course landing page, all the menus and buttons will be translated to Russian however my content remains which are dynamic is in portugese.

How do we handle such a scenerio?

**Comment by rotimi-best** [comment]
Udemy also has this flaw, pages are automatically translated based on my browser language.

however you can noticed that some parts of the page are in English. I will merge my PR in and should be fine until there is a legit reason to do otherwise.

![udemy-capture](https://github.com/user-attachments/assets/bcb64515-5ca2-41b1-8f7a-a2817426ee65)

**Comment by gabrieldesousah** [comment]
I think that the solution for it is a more complex solution (and a edge case): 
- completely translate course option: Multi-language created by AI and validated by the course admin
- Videos with caption and multiple dubbing or different videos for diferent language

This will probably not be used by most users, than is just "good to know", but it doesn't need to be done for now

**Comment by gabrieldesousah** [comment]
There is a glitch with this solution: When the page is loaded, is first in english and just after some ms it is translated. 
It works, but if can use a skeleton instead of another language is a better option

[Screenity video - Dec 29, 2024.webm](https://github.com/user-attachments/assets/d7c29ea9-7ec7-4702-bb76-91f18d3c4deb)

**Comment by rotimi-best** [comment]
> There is a glitch with this solution: When the page is loaded, is first in english and just after some ms it is translated. It works, but if can use a skeleton instead of another language is a better option
> 
>  Screenity.video.-.Dec.29.2024.webm

oh in this particular case, your browser language is portugese but since you are logged in and your language in your settings is English, that is why when we detect you are logged in (this happens on the client which is why you notice the switch), the page changes to english.

Try opening your course page in incognito mode, you won't see the glitch.

The ideal solution is for us to implement cookies based auth verification, which the server would know once the user is logged in. For now we don't have that functionality and we have an issue to move auth verification to the server using Supabase. At the time we implemented auth in ClassroomIO, supabase had not implemented that feature, now it has and we would need to revisit it. This will def improve the overall experience of the application.

**Comment by rotimi-best** [comment]
> I think that the solution for it is a more complex solution (and a edge case):
> 
> * completely translate course option: Multi-language created by AI and validated by the course admin
> * Videos with caption and multiple dubbing or different videos for diferent language
> 
> This will probably not be used by most users, than is just "good to know", but it doesn't need to be done for now

This is completely wild, the solution shouldn't be this complex though.

Ideally we should just allow for multiple translation of public page content just like we allow you set content for your lessons based on different languages. Even this would probably come later later further in our roadmap.

Then I think you should be able to set the languages you want your page to load in then a fallback to English if you don't have the translation.
