### ISSUE TITLE
Add project/workspace versioning and automatic changelog generation.

### ISSUE THREAD

**Issue by elvis-ndubuisi** [classroomio/classroomio#59]
### Improvement Description

I was thinking we should add semantic releases and changelogs to the project.

### Rationale

This feature can help
- Keep logs of major and minor releases on each projects in the repo
- Setup GitHub actions that handles deployment, tests, etc for each release type.
- Help determine which features/changes should come first (I think🤔)

**Comment by rotimi-best** [comment]
I completely agree. I have been thinking about this particular issue but wanted to better understand versioning and release circle of OS projects.

Thanks for bringing this up. are you working on it?

**Comment by rotimi-best** [comment]
Sounds good, please can you share with me how you plan on implementing this
